# This workflow generates a couple of artifacts that we use for testing

name: artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Generate test artifact alpha
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: artifact_alpha
        path: 'test/model/src/main/resources/artifact_alpha'
    - name: Generate test artifact beta
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: artifact_beta
        path: 'test/model/src/main/resources/artifact_beta'
